version: "3"

x-app: &configuration-base
  build:
    context: .
  env_file:
    - .env
  volumes:
    - .:/usr/src/app

services:
  mpa-db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - mpa-network
    ports:
      - "5433:5432"
    volumes:
      - dbvol:/var/lib/postgresql/data

  api:
    <<: *configuration-base

    command: bash -c "
      npx knex migrate:latest
      && npx nodemon src/serveur.ts
      "
    environment:
      - NODE_ENV=development
    networks:
      - mpa-network
      - lab-network
    ports:
      - "${PORT_MPA}:3001"
    depends_on:
      - mpa-db

networks:
  mpa-network:
    external: true
  lab-network:
    external: true

volumes:
  dbvol:
    driver: local
