name: L'intégration continue
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Construction de MonProfilANSSI

    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - name: Déterminer la version de Node.js à utiliser
        run: |
          echo "NODE_VERSION=$(./scripts/get-node-version.sh)" >> $GITHUB_ENV

      - name: Utiliser la version Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Installer les dépendances
        run: pnpm install

      - name: Contrôler le Typescript du Backend
        run: ./node_modules/.bin/tsc --noEmit

      - name: Exécuter les tests
        run: pnpm test
