name: L'intégration continue

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Construction de MonProfilANSSI

    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@v4

      - name: Déterminer la version de Node.js à utiliser
        run: |
          echo "NODE_VERSION=$(./scripts/get-node-version.sh)" >> $GITHUB_ENV

      - name: Utiliser la version Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Installer les dépendances
        run: npm ci

      - name: Contrôler le Typescript du Backend
        run: npx tsc --noEmit

      - name: Exécuter les tests
        run: npm test
